---
slug: about
title: "About"
date: "Last edited `r format(Sys.time(), '%B %d, %Y')`"
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
---

<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Site

I built the site using the R package [`blogdown`](https://bookdown.org/yihui/blogdown/) for a few reasons:

* To learn the (very) basics of web development.
* To encourage myself to read (and actually think about what I've learned). 
* To use R for something that didn't feel like work. 

The site is still very much a work-in-progress but I plan to write:

* Traditional blog posts 
    + Will be at the intersection of topics that I'm interested in and trying to learn more about, including:
        - Programming. 
        - Data Science (analytics, statistics, and machine learning).
        - Alternative approaches to economics (behavioural, complexity).
        - Evolutionary biology.
* Summaries.
    + Short notes on non-fiction books, academic papers, and textbooks. 
        - Focused on illustrating concepts using R.
        - Won't be exhaustive. 

# Education

I have a B.A. in Biological Sciences from the University of Oxford and an M.Sc. in Behavioural Economics from the University of Essex. 

# Employment

I currently work as a Junior Data Scientist in the Intelligence Team at a marketing agency called [SHARE](https://sharecreative.com/).

# Contact me

Contact me via any of the interactive icons on the homepage. 

I'll probably be most reponsive if you send me a message on [LinkedIn](https://www.linkedin.com/in/mitchelfruin/).