---
title: "Probability in the real world*"
date: "2019-08-15"
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Probability 101

## Probability vs. Statistics

Probability: Use known state of the world to predict the data we should observe.

* I have a fair coin (known state of the world) and can expect 50 heads and 50 tails, on average, from 100 flips (predicted data). 

Statistics: Use data we have observed to infer the most likely state of the world. 

* I flipped a coin 100 times and got 52 heads and 48 tails (observed data), I'm pretty sure that I have a fair coin (inferred state of the world). 

## Types of probability

Classic, based on symmetry. 

Frequentist, based on experience. 

Subjective, based on best guess. 

## Types of events

**Independent probabilities.** Should multiply. 

**Conditional probabilities.** Should use Bayes law. Visualise Bayesian updating with a contingency table/ infographic. 

## Puzzles

Sometimes probability is unintuitive. Birthday puzzle. 

# Legal problems

## Ignoring dependence

Sally Clark had two children dies from SIDS. Dr. Meadow, pediatrician, said there's 1 in 8543 chance of having a child die from SIDS giving a 1 in 73mil chance of having two children die from it. Potential genetic, environmental dependence ignored and she was sentenced for 3 years. Visualise Bayesian updating with a contingency table. Base rate neglect in medical test results. 

## The prosecutor's fallacy

**Prosecutor's fallacy:** False belief that conditional probabilities are invertible.

$$Pr(A|B) \neq Pr(B|A)$$

Forensics may compute that probability of blood at scene matching the defendent's by chance is 1%. That doesn't mean there's a 1% chance the defendent is innocent. We have been told the probability of a match given innocence, we want the probability of innocence given a match, but they don't equate:

$$Pr(\text{match}|\text{innocent}) \neq Pr(\text{innocent}|\text{match})$$

# Health problems

## Base rate neglect

# Research problems

# Statistical cognition

## The linda problem

Extra example of how we are intuitive statisticians. 

## All averages aren't made equal

Relative percentage change vs. absolute percentage change (i.e. percentage points) vs. natural frequencies. 