---
title: "Doughnut economics (Kate Raworth, 2017)."
author: "Mitchel Fruin"
date: "2019-08-10"
description: "Partial summary of doughnut economics by Kate Raworth."
tags: ["Economics", "Book summary"]
slug: doughnut_economics
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
    number_sections: true
---

<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

If you want to see the full code for this post then you can find the .Rmd file [here](https://github.com/mitchelfruin/MitchThinks/blob/master/content/posts/doughtnut_economics.Rmd).

Focus on diagrams is brilliant. Well worth reading.

Raworth proposes 7 changes to bring economics into the 21st century.

# Goal: GDP growth $\rightarrow$ The Doughnut.

* Summarise chapter.

# Big Picture: Self contained market $\rightarrow$ Embedded economy.

* Summarise chapter.

# Behavioural: Rational economic man $\rightarrow$ Social, adaptable humans.

* Summarise chapter.

# Complexity: Mechanical equilibrium $\rightarrow$ Dynamic complexity.

* Summarise chapter.

# Inequality: Growth will even it up $\rightarrow$ Distributive by design.

* Summarise chapter.

# Environment: Growth will clean it up $\rightarrow$ Regenerative by design.

* Summarise chapter.

# Growth: Growth addicted $\rightarrow$ Growth agnostic.

* Summarise chapter.

