---
title: "Nobody goes there anymore. It's too crowded."
date: "2019-08-28"
description: "Introduction to the 'El-Farol Bar Problem', a staple of complexity economics."
tags: ["Agent-based modelling", "Complexity", "Economics"]
slug: el_farol_bar_problem
draft: true
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
    number_sections: true
---

<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
# RMarkdown
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(igraph)
library(reshape2)
library(ggplot2)
```

# Introduction

I'm currently making my way through *Complexity and the Economy* by W. Brian Arthur. The book's second chapter is a paper from 1994 called [*Inductive Reasoning and Bounded Rationality: The El Farol Problem*](http://tuvalu.santafe.edu/~wbarthur/Papers/El_Farol.pdf). It's a fantastic example of how marrying psychological insights and a computational (rather than analytic) approach can produce novel, interesting, and intuive research in economics. So, I thought I'd have a go at reproducing the model described in the paper.   

# The El Farol bar problem

## Background 

When Arthur was working at the Santa Fe Institute in 1993, there was a bar called El Farol where people would go on a thursday night if they expected few people to be there, but would avoid if they expected it to be busy. This problem is interesting because it describes something of a paradox where beliefs lead to outcomes that cause those beliefs to be proved false. If people expect many others to attend, then few will show up and the bar will be empty. If people expect nobody to attend, then everyone will show up and it'll be packed. In both cases the original belief causes behaviour that means the belief ends up being incorrect.

Let's generalise this phenomenon in Arthur's toy model and see if we can gain any insight.  

## Model 



## Results

# Why should you care?

It exemplifies a common type of problem. 

It shows the value of numerical solutions to problems when analytical ones become too hard or are impossible (in this case because of inductive reasoning).  
