---
title: "NBA RDD"
author: "Mitchel Fruin"
date: "2020-04-19"
description: "Exploring NBA rookies' salaries using a regression discontinuity design."
tags: ["Probability and Statistics"]
slug: nba_rdd
draft: true
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
    number_sections: true
---

<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
# RMarkdown
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center",
                      fig.width = 8.09,
                      fig.height = 5)

# Packages
library(nbastatR)
```

```{r, eval = FALSE}
# Get draft data
nba_drafts <- drafts(draft_years = 1995:2019)

# Get bio data for each player in drafts
salaries <- bref_bios(players = nba_drafts$namePlayer,
                      player_ids = nba_drafts$idPlayer,
                      return_message = FALSE)
```




