---
title: "The Origin of Wealth (Eric Beinhocker, 2007)."
author: "Mitchel Fruin"
date: "2019-08-11"
description: "An introduction to complexity economics."
tags: ["Economics", "Complexity", "Book summary"]
slug: origin_wealth_complexity_economics
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
    number_sections: true
---

<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

If you want to see the code for this post then you can find the .Rmd file [here](https://github.com/mitchelfruin/MitchThinks/blob/master/content/books/origin_of_wealth.Rmd).

# Summary

In the first section of *The Origin of Wealth* Beinhocker outlines 5 key differences between traditional (neoclassical) economics and complexity economics:

1. Dynamics
2. Agents
3. Networks
4. Emergence
5. Evolution

I'll try to illustrate each in turn (the emphasised summaries heading each section are taken from Beinhocker without adaptation). 

# Dynamics

> Traditional: 
> 
> * Closed, static, linear systems in equilibrium
>
> Complexity:
> 
> * Open, dynamic, non-linear systems far from equilibrium

# Agents

> Traditional: 
>
>* Modelled collectively (homogenous)
>* Use complex deductive calculations to make decisions
>* Have complete information
>* Random errors (no biases)
>* No learning or adaptation (already optimal)
>
> Complexity:
>
>* Modelled individually (heterogenous)
>* Use inductive heuristics to make decisions
>* Have incomplete information
>* Some biases
>* Learn and adapt over time

# Networks

> Traditional:
>
>* Agents only interact indirectly through market mechanisms
>
> Complexity:
>
>* Explicitly model interactions between individual agents
>* Networks of relationships change over time 

# Emergence

> Traditional:
>
>* Separate disciplines for micro- and macroeconomics
>
> Complexity:
>
>* No hard distinction between micro- and macro-
>* Macro patterns are emergent result of mirco-level behaviours and interactions 

# Evolution 

> Traditional:
>
>* No mechanism for endogenously creating novelty, or growth in order/complexity
>
> Complexity:
>
>* Process of differentiation, selection, and amplification generates novelty and is responsible for economy's growth in order and complexity
