---
title: "Probability in the real world"
date: "2019-08-15"
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Probably not quite right

## Conditional probabilities

Sometimes probability is unintuitive. Birthday puzzle. 

**Types.** Classic, based on symmetry. Frequentist, based on experience. Subjective, based on best guess. 

**Independent probabilities.** Should multiply. 

**Dependent/Conditional probabilities.** Sally Clark had two children dies from SIDS. Dr. Meadow, pediatrician, said there's 1 in 8543 chance of having a child die from SIDS giving a 1 in 73mil chance of having two children die from it. Potential genetic, environmental dependence ignored and she was sentenced for 3 years. Visualise Bayesian updating with a contingency table. Base rate neglect in medical test results. 

## The prosecutor's fallacy

**Prosecutor's fallacy:** False belief that conditional probabilities are invertible when in fact they aren't.

$$Pr(A|B) \neq Pr(B|A)$$

Forensics may compute that probability of blood at scene matching the defendent's by chance is 1%. That doesn't mean there's a 1% chance the defendent is innocent. We have been told the probability of a match given innocence, we want the probability of innocence given a match, but they don't equate:

$$Pr(\text{match}|\text{innocent}) \neq Pr(\text{innocent}|\text{match})$$

## Bayesian updating